name: paginasconrutas
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  cupertino_icons: ^1.0.8

  # --- LIBRERÃAS AGREGADAS ---
  camera: ^0.11.0+2
  geolocator: ^10.1.0
  
  # qr_code_scanner causa error en Flutter Web â†’ SE DESACTIVA pero NO se elimina
  # qr_code_scanner: ^1.0.1

  permission_handler: ^11.3.1
  qr_flutter: ^4.1.0        # ğŸ“Œ GENERA EL QR  
  mobile_scanner: ^3.5.0    # ğŸ“Œ ESCANEA QR EN ANDROID / iOS / WEB SIN ERRORES
  geocoding: ^2.1.1         # ğŸ“Œ AGREGADO â†’ Convierte GPS a ciudad o direcciÃ³n  
  webview_flutter: ^4.7.0   # ğŸ“Œ AGREGADO â†’ Permite usar iframe en Flutter Web para mapas
  google_maps_flutter: ^2.9.0   # âœ… NUEVA LIBRERÃA â†’ Muestra mapa con GPS

  # ğŸŒ AGREGADO â†’ Compatible con Flutter Web y Windows (mapas OpenStreetMap)
  flutter_map: ^7.0.2
  latlong2: ^0.9.0

  # ğŸ’¾ AGREGADO â†’ Guardar usuario y contraseÃ±a localmente (para login/registro)
  shared_preferences: ^2.3.3
  # ---------------------------

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - images/trail.jpg
    - images/guia1.jpg
    - images/guia2.jpg
    - images/guia3.jpg
    - images/baÃ±os.jpg
    - images/mindo.jpg
    - images/rucu.jpg
    - images/quilotoa.jpg
