name: paginasconrutas
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.2.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

  # --- LIBRERÍAS ---
  camera: ^0.11.0+2
  geolocator: ^10.1.0
  permission_handler: ^11.4.0
  qr_flutter: ^4.1.0
  mobile_scanner: ^3.5.1
  geocoding: ^2.2.0
  webview_flutter: ^4.8.0
  google_maps_flutter: ^2.12.0
  flutter_map: ^7.0.2
  latlong2: ^0.9.1
  shared_preferences: ^2.3.4

  # --- FIREBASE (VERSIONES CORRECTAS PARA WEB + ANDROID) ---
  firebase_core: ^3.10.0
  firebase_auth: ^5.3.0
  cloud_firestore: ^5.4.4
  firebase_storage: ^12.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - images/trail.jpg
    - images/guia1.jpg
    - images/guia2.jpg
    - images/guia3.jpg
    - images/baños.jpg
    - images/mindo.jpg
    - images/rucu.jpg
    - images/quilotoa.jpg
